export default {
  LOGIN: "LOGIN",
  SIGNUP: "SIGNUP",
  VERIFY: "VERIFY",
  CATEGORIES: "CATEGORIES",
  CLEAR_REDUX_STATE: "CLEAR_REDUX_STATE",
  UPDATE_USER: "UPDATE_USER",
  USER_ADDRESS: "USER_ADDRESS",
  ADDRESS_ID: "ADDRESS_ID",
  CHECKBOX_ID: "CHECKBOX_ID",
  USER_ORDER: "USER_ORDER",
  PRODUCT: "PRODUCT",
  REVIEW: "REVIEW",
};
